name: paybliss
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter_local_notifications: any
  permission_handler: any
  eticon_api: any
  flutter_screenutil: any
  google_fonts: any
  flutter_svg: any
  loading_overlay_pro: ^2.1.1
  liquid_pull_to_refresh: ^3.0.1
  awesome_notifications: any
  flutter_onboarding_slider: ^1.0.9
  mask_input_formatter: any
  contained_tab_bar_view: any
  # shimmer: ^3.0.0
  intl: any
  searchfield: ^0.8.7
  image_picker: ^1.0.5
  dotted_border: ^2.1.0
  flutter_holo_date_picker: ^1.1.3
  flutter_animate: any
  searchable_paginated_dropdown: any
  textfield_search: any
  loadmore: any
  list_load_more: any
  url_launcher: any
  biometric_fingerprint: ^0.0.7
  custom_pin_screen: any
  flutter_any_logo: any
  lazy_load_refresh_indicator: any
  flutter_screen_lock: any
  icons_plus: any
  loading_animation_widget: any
  cool_dropdown: any
  video_player: any
  u_credit_card: any
  flutter_overlay_loader: any
  get_storage: any
  file_picker: ^6.1.1
  share_plus: any
  http: any
  get: 4.6.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.2
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/svg/
    - assets/images/
    - assets/json/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_img.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/logo_img-1152.png
  color_dark: "#000000"
  image_dark: assets/icons/logo_img-1152.png
